name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4

      - name: Setup pnpm and install dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - name: Run tests
        run: pnpm test

      - name: Build docs
        run: pnpm docs:build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER}}
          username: ${{ secrets.FTP_ACCOUNT}}
          password: ${{ secrets.FTP_PASSWORD}}
          server-dir: "/tools/"
          local-dir: "./.vitepress/dist/"